# Generated by Django 4.2.3 on 2023-07-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("hour", models.IntegerField()),
                ("credits", models.IntegerField()),
                ("state", models.BooleanField(default=True)),
            ],
        ),
    ]
