# Generated by Django 4.2.3 on 2023-07-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="state",
            field=models.BooleanField(),
        ),
    ]
