# Generated by Django 4.2.3 on 2023-07-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0002_alter_course_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=40),
        ),
    ]
