# Generated by Django 4.2.3 on 2023-07-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0003_alter_course_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("shortname", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="careers/"),
                ),
                ("state", models.BooleanField(default=True)),
            ],
        ),
    ]
