# Generated by Django 4.2.3 on 2023-07-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0004_career"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="image",
            field=models.ImageField(blank=True, upload_to="careers/"),
        ),
        migrations.AlterField(
            model_name="career",
            name="state",
            field=models.BooleanField(),
        ),
    ]
