# Generated by Django 4.2.3 on 2023-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0005_alter_career_image_alter_career_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="careers/"),
        ),
    ]
